const fs = require('fs');
const path = 'B:/GuPiaoUI/src/styles/global.css';
const NL = String.fromCharCode(10);
const Q = ';
const css = [
'/* === CSS Variables === */',
':root {',
'  --color-accent-a: #FF4D4D;',
'  --color-accent-b: #FFD60A;',
'  --color-accent-c: #00C2FF;',
'  --color-violet: #7B2FFF;',
'  --color-mint: #00E59B;',
'  --color-orange: #FF6B35;',
'  --color-pink: #FF006E;',
'  --color-text: #F5F5F5;',
'  --color-text-secondary: #AAAAAA;',
'  --color-bg: #0F172A;',
'  --font-heading: ' + Q + 'SmileySans' + Q + ', ' + Q + 'Microsoft YaHei' + Q + ', ' + Q + 'PingFang SC' + Q + ', sans-serif;',
'  --font-body: ' + Q + 'SmileySans' + Q + ', ' + Q + 'Microsoft YaHei' + Q + ', ' + Q + 'PingFang SC' + Q + ', sans-serif;',
'  --radius-sm: 8px;',
'  --radius-md: 12px;',
'  --radius-pill: 100px;',
'}',
'',
'/* === Font Face === */',
'@font-face {',
'  font-family: ' + Q + 'SmileySans' + Q + ';',
'  src: url(' + Q + '/fonts/SmileySans-Oblique-2.ttf' + Q + ') format(' + Q + 'truetype' + Q + ');',
'  font-weight: 500;',
'  font-style: oblique;',
'  font-display: swap;',
'}',
'',
'body { background: var(--color-bg); }',
'',
'.navbar { position: fixed; top: 0; left: 0; right: 0; z-index: 100; padding: 1rem 1.25rem; }',
'.navbar-inner { display: flex; align-items: center; justify-content: space-between; background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.15); border-radius: 100px; padding: 0.75rem 1.25rem; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 20px rgba(0,0,0,0.3); }',
'.nav-toggle { display: flex; background: none; border: none; cursor: pointer; padding: 0.5rem; flex-shrink: 0; }',
'.hamburger-lines { display: grid; grid-template-columns: 24px 2px; grid-template-rows: 2px 5px 2px; width: 24px; height: 9px; }',
'.hamburger-lines span { display: block; height: 2px; background: var(--color-text); border-radius: 2px; transition: all 0.3s ease; }',
'.hamburger-lines span:nth-child(1) { grid-column: 1; grid-row: 1; }',
'.hamburger-lines span:nth-child(2) { grid-column: 1; grid-row: 3; }',
'.nav-toggle.active .hamburger-lines span:nth-child(1) { grid-row: 2; transform: rotate(45deg); transform-origin: center; }',
'.nav-toggle.active .hamburger-lines span:nth-child(2) { grid-row: 2; transform: rotate(-45deg); transform-origin: center; }',
'.logo-circle { width: 40px; height: 40px; border-radius: 50%; background: var(--color-accent-a); color: white; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 1.1rem; text-decoration: none; flex-shrink: 0; transition: transform 0.2s ease; }',
'.logo-circle:hover { transform: scale(1.05); }',
'.logo-text { font-family: var(--font-heading); font-weight: 700; font-size: 1.2rem; color: var(--color-text); text-decoration: none; letter-spacing: -0.5px; }',
'.nav-logo-center { text-decoration: none; }',
'.nav-cards { display: none; position: absolute; top: calc(100% + 8px); left: 50%; transform: translateX(-50%); width: max-content; max-width: 600px; gap: 12px; }',
'.nav-cards.open { display: flex; flex-direction: row; animation: slideDown 0.3s ease; align-items: flex-start; }',
'@keyframes slideDown { from { opacity: 0; transform: translateX(-50%) translateY(-8px); } to { opacity: 1; transform: translateX(-50%) translateY(0); } }',
'.nav-card { border-radius: var(--radius-md); padding: 1rem; flex: 1; min-width: 0; border: none; box-shadow: 0 2px 8px rgba(0,0,0,0.2); }',
'.nav-card-about { background: var(--color-accent-a); }',
'.nav-card-work { background: var(--color-accent-c); }',
'.nav-card-contact { background: var(--color-mint); }',
'.nav-card-label { font-family: var(--font-heading); font-weight: 600; font-size: 0.9rem; margin-bottom: 0.75rem; padding-bottom: 0.5rem; border-bottom: 1px solid rgba(0,0,0,0.15); color: var(--color-text); }',
'.nav-card-links { display: flex; flex-direction: column; gap: 0.5rem; }',
'.nav-card-link { display: flex; align-items: center; gap: 0.5rem; text-decoration: none; color: var(--color-text); font-size: 0.85rem; font-weight: 500; padding: 0.4rem 0.6rem; border-radius: 6px; transition: all 0.2s ease; }',
'.nav-card-link:hover { background: rgba(0,0,0,0.1); color: var(--color-text); }',
'.nav-card-link svg { width: 16px; height: 16px; flex-shrink: 0; }',
'',
'.hero { height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; position: relative; overflow: hidden; background: linear-gradient(135deg, var(--color-accent-a) 0%, var(--color-accent-b) 50%, var(--color-accent-c) 100%); }',
'.hero-content { text-align: left; margin-left: 80px; margin-bottom: auto; padding-top: 4rem; }',
'.hero-content h1 { font-family: var(--font-heading); font-size: clamp(3rem, 8vw, 6rem); font-weight: 700; color: white; letter-spacing: -2px; line-height: 1; text-shadow: 0 2px 20px rgba(0,0,0,0.1); }',
'.hero-subtitle { font-family: var(--font-body); font-size: clamp(1rem, 2vw, 1.25rem); color: rgba(255,255,255,0.85); margin-top: 1rem; max-width: 500px; }',
'.hero-nav { position: absolute; bottom: 2rem; right: 2rem; display: flex; flex-direction: column; gap: 1.5rem; }',
'.nav-btn { width: 40px; height: 40px; border-radius: 50%; background: rgba(255,255,255,0.15); backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.25); display: flex; align-items: center; justify-content: center; color: white; font-size: 0.75rem; font-weight: 600; text-decoration: none; transition: all 0.3s ease; }',
'.nav-btn:hover { background: rgba(255,255,255,0.3); transform: scale(1.1); }',
'',
'.about-section { padding: 6rem 2rem 4rem; max-width: 1200px; margin: 0 auto; position: relative; }',
'.section-title { font-family: var(--font-heading); font-size: 2.5rem; font-weight: 700; color: var(--color-text); margin-bottom: 3rem; text-align: center; }',
'.about-grid { display: flex; flex-direction: column; align-items: center; position: relative; min-height: 800px; }',
'.about-row { display: flex; flex-direction: row; align-items: stretch; gap: 1.5rem; justify-content: center; width: 100%; margin-top: 1.5rem; }',
'.about-photo-wrapper { z-index: 2; margin-bottom: 2rem; }',
'.about-photo-placeholder { width: 160px; height: 160px; border-radius: 50%; background: rgba(255,255,255,0.06); border: 2px solid rgba(255,255,255,0.15); display: flex; align-items: center; justify-content: center; font-size: 0.9rem; color: var(--color-text-secondary); }',
'.about-card { padding: 1.5rem; border-radius: var(--radius-md); position: relative; width: 280px; flex-shrink: 0; }',
'.about-card h3 { font-family: var(--font-heading); font-size: 1.25rem; font-weight: 700; margin-bottom: 0.75rem; color: var(--color-text); }',
'.about-card p, .about-card .timeline-item, .about-card .exp-item { font-size: 0.9rem; line-height: 1.6; color: var(--color-text); }',
'.about-card .timeline-item, .about-card .exp-item { margin-bottom: 1rem; padding-bottom: 1rem; border-bottom: 1px solid rgba(0,0,0,0.1); }',
'.about-card .timeline-item:last-child, .about-card .exp-item:last-child { border-bottom: none; margin-bottom: 0; padding-bottom: 0; }',
'.timeline-year { display: block; font-weight: 600; font-size: 0.85rem; margin-bottom: 0.25rem; }',
'.timeline-title, .exp-role { display: block; font-weight: 600; font-size: 1rem; margin-bottom: 0.25rem; }',
'.timeline-school, .exp-period { display: block; font-size: 0.85rem; color: var(--color-text-secondary); margin-bottom: 0.5rem; }',
'.card-basic { background: var(--color-accent-b); transform: rotate(-2deg); }',
'.card-edu { background: var(--color-accent-c); transform: rotate(1.5deg); }',
'.card-exp { background: var(--color-mint); transform: rotate(-1deg); }',
'',
'.sticker { position: absolute; padding: 0.6rem 1.2rem; border-radius: var(--radius-sm); font-size: 0.85rem; font-weight: 600; color: white; white-space: nowrap; box-shadow: 0 4px 12px rgba(0,0,0,0.2), 0 1px 3px rgba(0,0,0,0.1); z-index: 3; pointer-events: auto; cursor: grab; user-select: none; -webkit-user-select: none; transition: box-shadow 0.3s ease, transform 0.2s ease; }',
'.sticker:hover { box-shadow: 0 8px 24px rgba(0,0,0,0.25), 0 2px 6px rgba(0,0,0,0.15); cursor: grabbing; }',
'.sticker-1 { background: var(--color-violet); top: 12%; right: 4%; transform: rotate(-6deg); }',
'.sticker-2 { background: var(--color-pink); top: 22%; left: 3%; transform: rotate(4deg); }',
'.sticker-3 { background: var(--color-orange); bottom: 18%; right: 6%; transform: rotate(-3deg); }',
'.sticker-4 { background: var(--color-accent-a); bottom: 28%; left: 5%; transform: rotate(8deg); }',
'.sticker-5 { background: var(--color-violet); top: 48%; right: 1%; transform: rotate(-5deg); }',
'.sticker-6 { background: var(--color-pink); top: 42%; left: 1%; transform: rotate(6deg); }',
'',
'.works-scroll { padding: 4rem 0 5rem; overflow: visible; border-top: 1px solid rgba(0,0,0,0.06); border-bottom: 1px solid rgba(0,0,0,0.06); }',
'.works-scroll .section-title { margin-left: 2rem; }',
'.works-container { display: flex; gap: 24px; width: max-content; animation: scrollWorks 25s linear infinite; padding: 0 2rem; }',
'.works-container.paused { animation-play-state: paused; }',
'.work-card { width: 220px; height: 140px; background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.1); border-radius: var(--radius-md); display: flex; align-items: center; justify-content: center; font-size: 1rem; font-weight: 600; color: var(--color-text); cursor: pointer; transition: all 0.3s ease; position: relative; overflow: visible; text-decoration: none; }',
'.work-card::before { content: ' + Q + '' + Q + '; position: absolute; inset: 0; background: linear-gradient(135deg, var(--color-accent-a), var(--color-accent-c)); opacity: 0; transition: opacity 0.3s ease; border-radius: inherit; }',
'.work-card:hover::before { opacity: 1; }',
'.work-card:hover { border-color: transparent; transform: scale(1.05); box-shadow: 0 8px 30px rgba(0,0,0,0.12); }',
'.work-card:hover .card-title { color: white; position: relative; z-index: 1; }',
'.card-title { position: relative; z-index: 1; transition: color 0.3s ease; }',
'@keyframes scrollWorks { 0% { transform: translateX(0); } 100% { transform: translateX(-50%); } }',
'',
'.contact-section { padding: 6rem 2rem; max-width: 800px; margin: 0 auto; text-align: center; }',
'.contact-content { margin-top: 2rem; }',
'.contact-text { font-size: 1.25rem; color: var(--color-text-secondary); margin-bottom: 1.5rem; }',
'.contact-email { display: inline-block; font-size: 1.5rem; font-weight: 600; font-family: var(--font-heading); color: var(--color-accent-a); border-bottom: 2px solid var(--color-accent-a); padding-bottom: 4px; text-decoration: none; transition: all 0.3s ease; }',
'.contact-email:hover { color: var(--color-accent-c); border-color: var(--color-accent-c); }',
'.contact-socials { display: flex; justify-content: center; gap: 2rem; margin-top: 2.5rem; flex-wrap: wrap; }',
'.social-link { font-size: 0.9rem; font-weight: 500; color: var(--color-text-secondary); padding: 8px 16px; border: 1px solid rgba(0,0,0,0.1); border-radius: var(--radius-pill); text-decoration: none; transition: all 0.3s ease; }',
'.social-link:hover { background: var(--color-text); color: var(--color-bg); border-color: var(--color-text); }',
'',
'.footer { text-align: center; padding: 3rem 2rem; color: var(--color-text-secondary); font-size: 0.85rem; border-top: 1px solid rgba(0,0,0,0.06); }',
'',
'@media (max-width: 768px) {',
'  .navbar { padding: 0.75rem; }',
'  .navbar-inner { padding: 0.5rem 1rem; }',
'  .logo-text { display: none; }',
'  .nav-toggle { display: flex; }',
'  .hero-content { margin-left: 0; text-align: center; padding-top: 2rem; }',
'  .hero-nav { left: 50%; transform: translateX(-50%); bottom: 2rem; flex-direction: row; gap: 1rem; }',
'  .about-section { padding: 3rem 1rem; }',
'  .about-grid { min-height: auto; }',
'  .about-card { transform: rotate(0deg) !important; width: 100% !important; margin-right: 0 !important; }',
'  .sticker { display: none; }',
'  .work-card { width: 180px; height: 110px; }',
'  .contact-email { font-size: 1.1rem; }',
'  .nav-cards { width: calc(100% - 2rem); max-width: none; }',
'}',
];
fs.writeFileSync(path, css.join(NL) + NL, 'utf8');
console.log('CSS written: ' + css.length + ' lines');
